config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tv_shows#index'

  resources :tv_shows do
    collection do
      post :add_as_favourite
      post :remove_as_favourite
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :tv_shows
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  belongs_to :channel
  acts_as_favoritable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_favoritor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  def index
    @tv_shows = TvShow.all
  end

  def add_as_favourite
    tv_show = TvShow.find(params[:id])
    current_user.favorite(tv_show)
    redirect_to root_path
  end

  def remove_as_favourite
    tv_show = TvShow.find(params[:id])
    current_user.unfavorite(tv_show)
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/layouts/_datatable_js.html.erb
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticalTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item active user-class">
        <% if current_user.present? %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Sign In", user_session_path, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
  </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

</html>

app/views/tv_shows/_get_data.html.erb
<% tv_shows.each do |tv_show| %>
  <tr>
    <td><%= tv_show.channel&.name %></td>
    <td><%= tv_show.name %></td>
    <td><%= tv_show.timing.strftime("%I:%M %p") %></td>
    <% if current_user.present? %>
      <% if current_user.favorited?(tv_show) %>
        <td><%= link_to 'Remove as Favourite', remove_as_favourite_tv_shows_path(id: tv_show.id), method: :post, class: 'btn btn-danger btn-sm' %></td>
      <% else %>
        <td><%= link_to 'Add as Favourite', add_as_favourite_tv_shows_path(id: tv_show.id), method: :post, class: 'btn btn-primary btn-sm' %></td>
      <% end %>
    <% else %>
      <td><%= link_to 'Add as Favourite', user_session_path,  class: 'btn btn-primary btn-sm' %></td>
    <% end %>
  </tr>
<% end %>

app/views/tv_shows/index.html.erb
<%= render partial: 'layouts/datatable_js' %>

<div class="container">
  <h2>TV Show List</h2>
  <table class="table table-bordered display" id="infoShow">
    <thead>
    <tr>
      <th>Channel Name</th>
      <th>Show Name</th>
      <th>Show Timing</th>
      <th>Add to Favourite</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: "get_data", :locals => { tv_shows: @tv_shows } %>
    </tbody>
  </table>
</div>

<script>
  $(document).ready(function() {
    $('#infoShow').DataTable();
  });
</script>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>